### ISSUE TITLE
Empty Feild

### ISSUE THREAD

**Issue by noob-master147** [TonyJac/Vision_based_ID_Reader#10]
Firebase lets store Empty Values

## Algorithm needs validations

**Comment by noob-master147** [comment]
![image](https://user-images.githubusercontent.com/43108912/78190825-62cef900-7492-11ea-906f-a4e1eff0e049.png)

**Comment by TonyJac** [comment]
That was from Rishi testing out from his branch. I haven't gone through that script. The master branch doesn't do that, each time I had tried it. Has it happened with you?

**Comment by noob-master147** [comment]
@TonyJac happened with me as well
and this doest make sense coz it wont append in the file unless it is not null

also this will be rectified as user will press n anyways but still "" blank should not show up in the 1st place
but any ways it is a good proactive to have a check just before the DB update.

**Comment by TonyJac** [comment]
With the new branch merge, this issue has been solved
