### ISSUE TITLE
Hashed data on terminal

### ISSUE THREAD

**Issue by noob-master147** [TonyJac/Vision_based_ID_Reader#5]
![image](https://user-images.githubusercontent.com/43108912/78181273-b422bc80-7481-11ea-9203-fda1167d3fc6.png)

**Comment by TonyJac** [comment]
It is not hashing, it's the unique entry ID on Firebase. Check the new version and see the change on console. 
![hep](https://user-images.githubusercontent.com/49027857/78183476-96efed00-7485-11ea-98be-093da49cdcf9.png)
