### ISSUE TITLE
add provision for extracting contact number as well

### ISSUE THREAD

**Issue by noob-master147** [TonyJac/Vision_based_ID_Reader#6]

**Comment by noob-master147** [comment]
The current model only gives the name and registration number of the participant

**There is still no tangible data to contact the participant back for updates**

**Comment by rish07** [comment]
Are you gonna scan the back of the ID card as well?

**Comment by noob-master147** [comment]
@rish07 yes

**Comment by TonyJac** [comment]
Check the recent entries in firebase. I used a modified script. Phone number detected and posted, but its not the correct phone number.

**Comment by TonyJac** [comment]
I pushed the code for extracting the phone number as well. 4/5 times, now it detects the right number
